/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AddImageToDocumentResponse = { 'ok' : bigint } |
  { 'error' : string };
export interface Channel {
  'id' : bigint,
  'name' : string,
  'createdBy' : Principal,
}
export type CreateDocumentResponse = { 'ok' : bigint } |
  { 'error' : string };
export type CreatePlayerDocumentResponse = { 'ok' : bigint } |
  { 'error' : string };
export interface DiceRollResult {
  'pattern' : string,
  'total' : bigint,
  'modifier' : bigint,
  'rolls' : Array<bigint>,
}
export interface Document {
  'id' : bigint,
  'content' : string,
  'name' : string,
  'createdBy' : Principal,
  'locked' : boolean,
  'lastModified' : bigint,
  'sessionId' : bigint,
  'revision' : bigint,
}
export interface DocumentComment {
  'id' : bigint,
  'text' : string,
  'author' : Principal,
  'timestamp' : Time,
  'documentId' : bigint,
}
export interface DocumentFileReference {
  'id' : bigint,
  'file' : ExternalBlob,
  'createdBy' : Principal,
  'size' : bigint,
  'mimeType' : string,
  'filename' : string,
  'lastModified' : bigint,
  'documentId' : bigint,
}
export interface DocumentWithImages {
  'id' : bigint,
  'content' : string,
  'name' : string,
  'createdBy' : Principal,
  'locked' : boolean,
  'lastModified' : bigint,
  'sessionId' : bigint,
  'revision' : bigint,
  'images' : Array<ImageReference>,
}
export type ExternalBlob = Uint8Array;
export interface ImageReference {
  'id' : bigint,
  'title' : string,
  'createdBy' : Principal,
  'size' : bigint,
  'lastModified' : bigint,
  'fileId' : string,
  'caption' : string,
  'documentId' : bigint,
  'position' : bigint,
}
export interface JoinSessionRequest {
  'nickname' : string,
  'password' : [] | [string],
  'sessionId' : bigint,
}
export interface MembersChannel {
  'id' : bigint,
  'name' : string,
  'createdBy' : Principal,
}
export interface Message {
  'id' : bigint,
  'content' : string,
  'channelId' : bigint,
  'author' : string,
  'timestamp' : bigint,
  'image' : [] | [ExternalBlob],
  'replyToId' : [] | [bigint],
}
export interface PlayerDocument {
  'id' : bigint,
  'content' : string,
  'owner' : Principal,
  'name' : string,
  'createdBy' : Principal,
  'lastModified' : bigint,
  'isPrivate' : boolean,
  'sessionId' : bigint,
  'images' : Array<ImageReference>,
}
export interface PlayerDocumentMetadata {
  'id' : bigint,
  'owner' : Principal,
  'name' : string,
  'createdBy' : Principal,
  'lastModified' : bigint,
  'isPrivate' : boolean,
  'sessionId' : bigint,
}
export interface Session {
  'id' : bigint,
  'members' : Array<SessionMember>,
  'host' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'channels' : Array<Channel>,
  'membersChannels' : Array<MembersChannel>,
  'passwordHash' : [] | [Uint8Array],
  'lastActive' : bigint,
}
export interface SessionCreateRequest {
  'password' : [] | [string],
  'name' : string,
  'hostNickname' : string,
}
export interface SessionExport {
  'playerDocuments' : Array<PlayerDocument>,
  'turnOrder' : [] | [TurnOrder],
  'documents' : Array<Document>,
  'messages' : Array<Message>,
  'channels' : Array<Channel>,
  'session' : Session,
  'documentFiles' : Array<DocumentFileReference>,
  'images' : Array<ImageReference>,
}
export interface SessionMember {
  'id' : Principal,
  'nickname' : string,
  'joinedAt' : bigint,
}
export type StandardResponse = { 'ok' : string } |
  { 'error' : string };
export type Time = bigint;
export interface TurnOrder {
  'currentIndex' : bigint,
  'order' : Array<string>,
  'sessionId' : bigint,
}
export type UploadDocumentFileResponse = { 'ok' : bigint } |
  { 'error' : string };
export interface UploadFileRequest {
  'file' : ExternalBlob,
  'size' : bigint,
  'mimeType' : string,
  'filename' : string,
  'documentId' : bigint,
}
export interface UserProfile {
  'name' : string,
  'profilePicture' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string], bigint>,
  'addImageToDocument' : ActorMethod<
    [bigint, bigint, string, string, string, bigint, bigint],
    AddImageToDocumentResponse
  >,
  'addImageToPlayerDocument' : ActorMethod<
    [bigint, string, string, string, bigint, bigint],
    AddImageToDocumentResponse
  >,
  'addPlayerImage' : ActorMethod<
    [bigint, string, string, string, bigint, bigint],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createChannel' : ActorMethod<[bigint, string], StandardResponse>,
  'createDocument' : ActorMethod<
    [bigint, string, string],
    CreateDocumentResponse
  >,
  'createMembersChannel' : ActorMethod<[bigint, string], StandardResponse>,
  'createPlayerDocument' : ActorMethod<
    [bigint, string, string, boolean],
    CreatePlayerDocumentResponse
  >,
  'createSession' : ActorMethod<[SessionCreateRequest], Session>,
  'deleteChannel' : ActorMethod<[bigint, bigint], StandardResponse>,
  'deleteComment' : ActorMethod<[bigint], undefined>,
  'deleteDocument' : ActorMethod<[bigint], StandardResponse>,
  'deleteMembersChannel' : ActorMethod<[bigint, bigint], StandardResponse>,
  'deletePlayerDocument' : ActorMethod<[bigint], StandardResponse>,
  'editDocument' : ActorMethod<[bigint, string], StandardResponse>,
  'editPlayerDocument' : ActorMethod<[bigint, string], StandardResponse>,
  'exportSession' : ActorMethod<[bigint], [] | [SessionExport]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChannels' : ActorMethod<[bigint], Array<Channel>>,
  'getComments' : ActorMethod<[bigint], Array<DocumentComment>>,
  'getDocument' : ActorMethod<[bigint], [] | [Document]>,
  'getDocumentFileBlob' : ActorMethod<[bigint], [] | [ExternalBlob]>,
  'getDocumentFileReference' : ActorMethod<
    [bigint],
    [] | [DocumentFileReference]
  >,
  'getDocumentWithImages' : ActorMethod<[bigint], [] | [DocumentWithImages]>,
  'getImageReferences' : ActorMethod<[bigint], Array<ImageReference>>,
  'getImages' : ActorMethod<[bigint], Array<ImageReference>>,
  'getMembersChannels' : ActorMethod<[bigint], Array<MembersChannel>>,
  'getMessages' : ActorMethod<[bigint, bigint], Array<Message>>,
  'getPlayerDocument' : ActorMethod<[bigint], [] | [PlayerDocument]>,
  'getSession' : ActorMethod<[bigint], [] | [Session]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'importSession' : ActorMethod<[SessionExport], StandardResponse>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinSession' : ActorMethod<[JoinSessionRequest], StandardResponse>,
  'listDocumentFiles' : ActorMethod<[bigint], Array<DocumentFileReference>>,
  'listDocuments' : ActorMethod<[bigint], Array<Document>>,
  'listPlayerDocuments' : ActorMethod<[bigint], Array<PlayerDocument>>,
  'listPlayerDocumentsMetadata' : ActorMethod<
    [bigint],
    Array<PlayerDocumentMetadata>
  >,
  'listSessions' : ActorMethod<[], Array<Session>>,
  'lockDocument' : ActorMethod<[bigint], StandardResponse>,
  'nextTurn' : ActorMethod<[bigint], StandardResponse>,
  'postMessage' : ActorMethod<
    [bigint, bigint, string, [] | [ExternalBlob], [] | [bigint]],
    StandardResponse
  >,
  'removeProfilePicture' : ActorMethod<[], undefined>,
  'renameChannel' : ActorMethod<[bigint, bigint, string], StandardResponse>,
  'renameDocument' : ActorMethod<[bigint, string], StandardResponse>,
  'renameMembersChannel' : ActorMethod<
    [bigint, bigint, string],
    StandardResponse
  >,
  'renamePlayerDocument' : ActorMethod<[bigint, string], StandardResponse>,
  'roll' : ActorMethod<[bigint, string], DiceRollResult>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setPlayerDocumentVisibility' : ActorMethod<
    [bigint, boolean],
    StandardResponse
  >,
  'setTurnOrder' : ActorMethod<[bigint, Array<string>], StandardResponse>,
  'unlockDocument' : ActorMethod<[bigint], StandardResponse>,
  'updateComment' : ActorMethod<[bigint, string], undefined>,
  'uploadDocumentFile' : ActorMethod<
    [UploadFileRequest],
    UploadDocumentFileResponse
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];