/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AddImageToDocumentResponse = IDL.Variant({
  'ok' : IDL.Nat,
  'error' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StandardResponse = IDL.Variant({
  'ok' : IDL.Text,
  'error' : IDL.Text,
});
export const CreateDocumentResponse = IDL.Variant({
  'ok' : IDL.Nat,
  'error' : IDL.Text,
});
export const CreatePlayerDocumentResponse = IDL.Variant({
  'ok' : IDL.Nat,
  'error' : IDL.Text,
});
export const SessionCreateRequest = IDL.Record({
  'password' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'hostNickname' : IDL.Text,
});
export const SessionMember = IDL.Record({
  'id' : IDL.Principal,
  'nickname' : IDL.Text,
  'joinedAt' : IDL.Int,
});
export const Channel = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
});
export const MembersChannel = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
});
export const Session = IDL.Record({
  'id' : IDL.Nat,
  'members' : IDL.Vec(SessionMember),
  'host' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'channels' : IDL.Vec(Channel),
  'membersChannels' : IDL.Vec(MembersChannel),
  'passwordHash' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'lastActive' : IDL.Int,
});
export const ImageReference = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdBy' : IDL.Principal,
  'size' : IDL.Int,
  'lastModified' : IDL.Int,
  'fileId' : IDL.Text,
  'caption' : IDL.Text,
  'documentId' : IDL.Nat,
  'position' : IDL.Int,
});
export const PlayerDocument = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
  'lastModified' : IDL.Int,
  'isPrivate' : IDL.Bool,
  'sessionId' : IDL.Nat,
  'images' : IDL.Vec(ImageReference),
});
export const TurnOrder = IDL.Record({
  'currentIndex' : IDL.Nat,
  'order' : IDL.Vec(IDL.Text),
  'sessionId' : IDL.Nat,
});
export const Document = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
  'locked' : IDL.Bool,
  'lastModified' : IDL.Int,
  'sessionId' : IDL.Nat,
  'revision' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'channelId' : IDL.Nat,
  'author' : IDL.Text,
  'timestamp' : IDL.Int,
  'image' : IDL.Opt(ExternalBlob),
  'replyToId' : IDL.Opt(IDL.Nat),
});
export const DocumentFileReference = IDL.Record({
  'id' : IDL.Nat,
  'file' : ExternalBlob,
  'createdBy' : IDL.Principal,
  'size' : IDL.Nat,
  'mimeType' : IDL.Text,
  'filename' : IDL.Text,
  'lastModified' : IDL.Int,
  'documentId' : IDL.Nat,
});
export const SessionExport = IDL.Record({
  'playerDocuments' : IDL.Vec(PlayerDocument),
  'turnOrder' : IDL.Opt(TurnOrder),
  'documents' : IDL.Vec(Document),
  'messages' : IDL.Vec(Message),
  'channels' : IDL.Vec(Channel),
  'session' : Session,
  'documentFiles' : IDL.Vec(DocumentFileReference),
  'images' : IDL.Vec(ImageReference),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'profilePicture' : IDL.Opt(ExternalBlob),
});
export const Time = IDL.Int;
export const DocumentComment = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'documentId' : IDL.Nat,
});
export const DocumentWithImages = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
  'locked' : IDL.Bool,
  'lastModified' : IDL.Int,
  'sessionId' : IDL.Nat,
  'revision' : IDL.Nat,
  'images' : IDL.Vec(ImageReference),
});
export const JoinSessionRequest = IDL.Record({
  'nickname' : IDL.Text,
  'password' : IDL.Opt(IDL.Text),
  'sessionId' : IDL.Nat,
});
export const PlayerDocumentMetadata = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
  'lastModified' : IDL.Int,
  'isPrivate' : IDL.Bool,
  'sessionId' : IDL.Nat,
});
export const DiceRollResult = IDL.Record({
  'pattern' : IDL.Text,
  'total' : IDL.Int,
  'modifier' : IDL.Int,
  'rolls' : IDL.Vec(IDL.Nat),
});
export const UploadFileRequest = IDL.Record({
  'file' : ExternalBlob,
  'size' : IDL.Nat,
  'mimeType' : IDL.Text,
  'filename' : IDL.Text,
  'documentId' : IDL.Nat,
});
export const UploadDocumentFileResponse = IDL.Variant({
  'ok' : IDL.Nat,
  'error' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'addImageToDocument' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Int],
      [AddImageToDocumentResponse],
      [],
    ),
  'addImageToPlayerDocument' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Int],
      [AddImageToDocumentResponse],
      [],
    ),
  'addPlayerImage' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Int],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createChannel' : IDL.Func([IDL.Nat, IDL.Text], [StandardResponse], []),
  'createDocument' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [CreateDocumentResponse],
      [],
    ),
  'createMembersChannel' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [StandardResponse],
      [],
    ),
  'createPlayerDocument' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Bool],
      [CreatePlayerDocumentResponse],
      [],
    ),
  'createSession' : IDL.Func([SessionCreateRequest], [Session], []),
  'deleteChannel' : IDL.Func([IDL.Nat, IDL.Nat], [StandardResponse], []),
  'deleteComment' : IDL.Func([IDL.Nat], [], []),
  'deleteDocument' : IDL.Func([IDL.Nat], [StandardResponse], []),
  'deleteMembersChannel' : IDL.Func([IDL.Nat, IDL.Nat], [StandardResponse], []),
  'deletePlayerDocument' : IDL.Func([IDL.Nat], [StandardResponse], []),
  'editDocument' : IDL.Func([IDL.Nat, IDL.Text], [StandardResponse], []),
  'editPlayerDocument' : IDL.Func([IDL.Nat, IDL.Text], [StandardResponse], []),
  'exportSession' : IDL.Func([IDL.Nat], [IDL.Opt(SessionExport)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChannels' : IDL.Func([IDL.Nat], [IDL.Vec(Channel)], ['query']),
  'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(DocumentComment)], ['query']),
  'getDocument' : IDL.Func([IDL.Nat], [IDL.Opt(Document)], ['query']),
  'getDocumentFileBlob' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ExternalBlob)],
      ['query'],
    ),
  'getDocumentFileReference' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(DocumentFileReference)],
      ['query'],
    ),
  'getDocumentWithImages' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(DocumentWithImages)],
      ['query'],
    ),
  'getImageReferences' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ImageReference)],
      ['query'],
    ),
  'getImages' : IDL.Func([IDL.Nat], [IDL.Vec(ImageReference)], ['query']),
  'getMembersChannels' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(MembersChannel)],
      ['query'],
    ),
  'getMessages' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Message)], ['query']),
  'getPlayerDocument' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(PlayerDocument)],
      ['query'],
    ),
  'getSession' : IDL.Func([IDL.Nat], [IDL.Opt(Session)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'importSession' : IDL.Func([SessionExport], [StandardResponse], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinSession' : IDL.Func([JoinSessionRequest], [StandardResponse], []),
  'listDocumentFiles' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(DocumentFileReference)],
      ['query'],
    ),
  'listDocuments' : IDL.Func([IDL.Nat], [IDL.Vec(Document)], ['query']),
  'listPlayerDocuments' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(PlayerDocument)],
      ['query'],
    ),
  'listPlayerDocumentsMetadata' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(PlayerDocumentMetadata)],
      ['query'],
    ),
  'listSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'lockDocument' : IDL.Func([IDL.Nat], [StandardResponse], []),
  'nextTurn' : IDL.Func([IDL.Nat], [StandardResponse], []),
  'postMessage' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Nat)],
      [StandardResponse],
      [],
    ),
  'removeProfilePicture' : IDL.Func([], [], []),
  'renameChannel' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text],
      [StandardResponse],
      [],
    ),
  'renameDocument' : IDL.Func([IDL.Nat, IDL.Text], [StandardResponse], []),
  'renameMembersChannel' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text],
      [StandardResponse],
      [],
    ),
  'renamePlayerDocument' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [StandardResponse],
      [],
    ),
  'roll' : IDL.Func([IDL.Nat, IDL.Text], [DiceRollResult], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setPlayerDocumentVisibility' : IDL.Func(
      [IDL.Nat, IDL.Bool],
      [StandardResponse],
      [],
    ),
  'setTurnOrder' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Text)],
      [StandardResponse],
      [],
    ),
  'unlockDocument' : IDL.Func([IDL.Nat], [StandardResponse], []),
  'updateComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'uploadDocumentFile' : IDL.Func(
      [UploadFileRequest],
      [UploadDocumentFileResponse],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AddImageToDocumentResponse = IDL.Variant({
    'ok' : IDL.Nat,
    'error' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StandardResponse = IDL.Variant({ 'ok' : IDL.Text, 'error' : IDL.Text });
  const CreateDocumentResponse = IDL.Variant({
    'ok' : IDL.Nat,
    'error' : IDL.Text,
  });
  const CreatePlayerDocumentResponse = IDL.Variant({
    'ok' : IDL.Nat,
    'error' : IDL.Text,
  });
  const SessionCreateRequest = IDL.Record({
    'password' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'hostNickname' : IDL.Text,
  });
  const SessionMember = IDL.Record({
    'id' : IDL.Principal,
    'nickname' : IDL.Text,
    'joinedAt' : IDL.Int,
  });
  const Channel = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
  });
  const MembersChannel = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
  });
  const Session = IDL.Record({
    'id' : IDL.Nat,
    'members' : IDL.Vec(SessionMember),
    'host' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'channels' : IDL.Vec(Channel),
    'membersChannels' : IDL.Vec(MembersChannel),
    'passwordHash' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'lastActive' : IDL.Int,
  });
  const ImageReference = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdBy' : IDL.Principal,
    'size' : IDL.Int,
    'lastModified' : IDL.Int,
    'fileId' : IDL.Text,
    'caption' : IDL.Text,
    'documentId' : IDL.Nat,
    'position' : IDL.Int,
  });
  const PlayerDocument = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
    'lastModified' : IDL.Int,
    'isPrivate' : IDL.Bool,
    'sessionId' : IDL.Nat,
    'images' : IDL.Vec(ImageReference),
  });
  const TurnOrder = IDL.Record({
    'currentIndex' : IDL.Nat,
    'order' : IDL.Vec(IDL.Text),
    'sessionId' : IDL.Nat,
  });
  const Document = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
    'locked' : IDL.Bool,
    'lastModified' : IDL.Int,
    'sessionId' : IDL.Nat,
    'revision' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'channelId' : IDL.Nat,
    'author' : IDL.Text,
    'timestamp' : IDL.Int,
    'image' : IDL.Opt(ExternalBlob),
    'replyToId' : IDL.Opt(IDL.Nat),
  });
  const DocumentFileReference = IDL.Record({
    'id' : IDL.Nat,
    'file' : ExternalBlob,
    'createdBy' : IDL.Principal,
    'size' : IDL.Nat,
    'mimeType' : IDL.Text,
    'filename' : IDL.Text,
    'lastModified' : IDL.Int,
    'documentId' : IDL.Nat,
  });
  const SessionExport = IDL.Record({
    'playerDocuments' : IDL.Vec(PlayerDocument),
    'turnOrder' : IDL.Opt(TurnOrder),
    'documents' : IDL.Vec(Document),
    'messages' : IDL.Vec(Message),
    'channels' : IDL.Vec(Channel),
    'session' : Session,
    'documentFiles' : IDL.Vec(DocumentFileReference),
    'images' : IDL.Vec(ImageReference),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'profilePicture' : IDL.Opt(ExternalBlob),
  });
  const Time = IDL.Int;
  const DocumentComment = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'documentId' : IDL.Nat,
  });
  const DocumentWithImages = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
    'locked' : IDL.Bool,
    'lastModified' : IDL.Int,
    'sessionId' : IDL.Nat,
    'revision' : IDL.Nat,
    'images' : IDL.Vec(ImageReference),
  });
  const JoinSessionRequest = IDL.Record({
    'nickname' : IDL.Text,
    'password' : IDL.Opt(IDL.Text),
    'sessionId' : IDL.Nat,
  });
  const PlayerDocumentMetadata = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
    'lastModified' : IDL.Int,
    'isPrivate' : IDL.Bool,
    'sessionId' : IDL.Nat,
  });
  const DiceRollResult = IDL.Record({
    'pattern' : IDL.Text,
    'total' : IDL.Int,
    'modifier' : IDL.Int,
    'rolls' : IDL.Vec(IDL.Nat),
  });
  const UploadFileRequest = IDL.Record({
    'file' : ExternalBlob,
    'size' : IDL.Nat,
    'mimeType' : IDL.Text,
    'filename' : IDL.Text,
    'documentId' : IDL.Nat,
  });
  const UploadDocumentFileResponse = IDL.Variant({
    'ok' : IDL.Nat,
    'error' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'addImageToDocument' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Int],
        [AddImageToDocumentResponse],
        [],
      ),
    'addImageToPlayerDocument' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Int],
        [AddImageToDocumentResponse],
        [],
      ),
    'addPlayerImage' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Int],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createChannel' : IDL.Func([IDL.Nat, IDL.Text], [StandardResponse], []),
    'createDocument' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [CreateDocumentResponse],
        [],
      ),
    'createMembersChannel' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [StandardResponse],
        [],
      ),
    'createPlayerDocument' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Bool],
        [CreatePlayerDocumentResponse],
        [],
      ),
    'createSession' : IDL.Func([SessionCreateRequest], [Session], []),
    'deleteChannel' : IDL.Func([IDL.Nat, IDL.Nat], [StandardResponse], []),
    'deleteComment' : IDL.Func([IDL.Nat], [], []),
    'deleteDocument' : IDL.Func([IDL.Nat], [StandardResponse], []),
    'deleteMembersChannel' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [StandardResponse],
        [],
      ),
    'deletePlayerDocument' : IDL.Func([IDL.Nat], [StandardResponse], []),
    'editDocument' : IDL.Func([IDL.Nat, IDL.Text], [StandardResponse], []),
    'editPlayerDocument' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [StandardResponse],
        [],
      ),
    'exportSession' : IDL.Func([IDL.Nat], [IDL.Opt(SessionExport)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChannels' : IDL.Func([IDL.Nat], [IDL.Vec(Channel)], ['query']),
    'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(DocumentComment)], ['query']),
    'getDocument' : IDL.Func([IDL.Nat], [IDL.Opt(Document)], ['query']),
    'getDocumentFileBlob' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ExternalBlob)],
        ['query'],
      ),
    'getDocumentFileReference' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(DocumentFileReference)],
        ['query'],
      ),
    'getDocumentWithImages' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(DocumentWithImages)],
        ['query'],
      ),
    'getImageReferences' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ImageReference)],
        ['query'],
      ),
    'getImages' : IDL.Func([IDL.Nat], [IDL.Vec(ImageReference)], ['query']),
    'getMembersChannels' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MembersChannel)],
        ['query'],
      ),
    'getMessages' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Message)], ['query']),
    'getPlayerDocument' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PlayerDocument)],
        ['query'],
      ),
    'getSession' : IDL.Func([IDL.Nat], [IDL.Opt(Session)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'importSession' : IDL.Func([SessionExport], [StandardResponse], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinSession' : IDL.Func([JoinSessionRequest], [StandardResponse], []),
    'listDocumentFiles' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(DocumentFileReference)],
        ['query'],
      ),
    'listDocuments' : IDL.Func([IDL.Nat], [IDL.Vec(Document)], ['query']),
    'listPlayerDocuments' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(PlayerDocument)],
        ['query'],
      ),
    'listPlayerDocumentsMetadata' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(PlayerDocumentMetadata)],
        ['query'],
      ),
    'listSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'lockDocument' : IDL.Func([IDL.Nat], [StandardResponse], []),
    'nextTurn' : IDL.Func([IDL.Nat], [StandardResponse], []),
    'postMessage' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Nat)],
        [StandardResponse],
        [],
      ),
    'removeProfilePicture' : IDL.Func([], [], []),
    'renameChannel' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text],
        [StandardResponse],
        [],
      ),
    'renameDocument' : IDL.Func([IDL.Nat, IDL.Text], [StandardResponse], []),
    'renameMembersChannel' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text],
        [StandardResponse],
        [],
      ),
    'renamePlayerDocument' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [StandardResponse],
        [],
      ),
    'roll' : IDL.Func([IDL.Nat, IDL.Text], [DiceRollResult], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setPlayerDocumentVisibility' : IDL.Func(
        [IDL.Nat, IDL.Bool],
        [StandardResponse],
        [],
      ),
    'setTurnOrder' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Text)],
        [StandardResponse],
        [],
      ),
    'unlockDocument' : IDL.Func([IDL.Nat], [StandardResponse], []),
    'updateComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'uploadDocumentFile' : IDL.Func(
        [UploadFileRequest],
        [UploadDocumentFileResponse],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };