/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const StandardResponse = IDL.Variant({
  'ok' : IDL.Text,
  'error' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'profilePicture' : IDL.Opt(ExternalBlob),
});
export const Community = IDL.Record({
  'id' : IDL.Nat,
  'font' : IDL.Opt(IDL.Text),
  'host' : IDL.Principal,
  'primaryColor' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'accentColor' : IDL.Opt(IDL.Text),
  'layoutOptions' : IDL.Opt(IDL.Text),
  'bannerImage' : IDL.Opt(ExternalBlob),
});
export const Time = IDL.Int;
export const CommunityPost = IDL.Record({
  'id' : IDL.Nat,
  'communityId' : IDL.Nat,
  'text' : IDL.Text,
  'authorName' : IDL.Text,
  'timestamp' : Time,
  'image' : IDL.Opt(ExternalBlob),
  'authorPrincipal' : IDL.Principal,
});
export const Tab = IDL.Variant({
  'chat' : IDL.Null,
  'home' : IDL.Null,
  'lore' : IDL.Null,
  'polls' : IDL.Null,
  'quizzes' : IDL.Null,
  'rules' : IDL.Null,
});
export const TabData = IDL.Record({
  'tab' : Tab,
  'order' : IDL.Nat,
  'canReorderMember' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'canReorder' : IDL.Func([IDL.Nat, IDL.Principal], [IDL.Bool], ['query']),
  'createCommunity' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'error' : IDL.Text })],
      [],
    ),
  'createCommunityPost' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [StandardResponse],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommunity' : IDL.Func([IDL.Nat], [IDL.Opt(Community)], ['query']),
  'getCommunityPosts' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CommunityPost)],
      ['query'],
    ),
  'getMemberTabReorderPermissions' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Bool))],
      ['query'],
    ),
  'getTabs' : IDL.Func([IDL.Nat], [IDL.Vec(TabData)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reorderTabs' : IDL.Func([IDL.Nat, IDL.Vec(Tab)], [StandardResponse], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCommunitySettings' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(ExternalBlob),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [StandardResponse],
      [],
    ),
  'updateMemberTabReorderPermission' : IDL.Func(
      [IDL.Nat, IDL.Principal, IDL.Bool],
      [StandardResponse],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const StandardResponse = IDL.Variant({ 'ok' : IDL.Text, 'error' : IDL.Text });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'profilePicture' : IDL.Opt(ExternalBlob),
  });
  const Community = IDL.Record({
    'id' : IDL.Nat,
    'font' : IDL.Opt(IDL.Text),
    'host' : IDL.Principal,
    'primaryColor' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'accentColor' : IDL.Opt(IDL.Text),
    'layoutOptions' : IDL.Opt(IDL.Text),
    'bannerImage' : IDL.Opt(ExternalBlob),
  });
  const Time = IDL.Int;
  const CommunityPost = IDL.Record({
    'id' : IDL.Nat,
    'communityId' : IDL.Nat,
    'text' : IDL.Text,
    'authorName' : IDL.Text,
    'timestamp' : Time,
    'image' : IDL.Opt(ExternalBlob),
    'authorPrincipal' : IDL.Principal,
  });
  const Tab = IDL.Variant({
    'chat' : IDL.Null,
    'home' : IDL.Null,
    'lore' : IDL.Null,
    'polls' : IDL.Null,
    'quizzes' : IDL.Null,
    'rules' : IDL.Null,
  });
  const TabData = IDL.Record({
    'tab' : Tab,
    'order' : IDL.Nat,
    'canReorderMember' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'canReorder' : IDL.Func([IDL.Nat, IDL.Principal], [IDL.Bool], ['query']),
    'createCommunity' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'error' : IDL.Text })],
        [],
      ),
    'createCommunityPost' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [StandardResponse],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommunity' : IDL.Func([IDL.Nat], [IDL.Opt(Community)], ['query']),
    'getCommunityPosts' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CommunityPost)],
        ['query'],
      ),
    'getMemberTabReorderPermissions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Bool))],
        ['query'],
      ),
    'getTabs' : IDL.Func([IDL.Nat], [IDL.Vec(TabData)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reorderTabs' : IDL.Func([IDL.Nat, IDL.Vec(Tab)], [StandardResponse], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCommunitySettings' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(ExternalBlob),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [StandardResponse],
        [],
      ),
    'updateMemberTabReorderPermission' : IDL.Func(
        [IDL.Nat, IDL.Principal, IDL.Bool],
        [StandardResponse],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };