/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Community {
  'id' : bigint,
  'font' : [] | [string],
  'host' : Principal,
  'primaryColor' : [] | [string],
  'name' : string,
  'accentColor' : [] | [string],
  'layoutOptions' : [] | [string],
  'bannerImage' : [] | [ExternalBlob],
}
export interface CommunityPost {
  'id' : bigint,
  'communityId' : bigint,
  'text' : string,
  'authorName' : string,
  'timestamp' : Time,
  'image' : [] | [ExternalBlob],
  'authorPrincipal' : Principal,
}
export type ExternalBlob = Uint8Array;
export type StandardResponse = { 'ok' : string } |
  { 'error' : string };
export type Tab = { 'chat' : null } |
  { 'home' : null } |
  { 'lore' : null } |
  { 'polls' : null } |
  { 'quizzes' : null } |
  { 'rules' : null };
export interface TabData {
  'tab' : Tab,
  'order' : bigint,
  'canReorderMember' : boolean,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'profilePicture' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'canReorder' : ActorMethod<[bigint, Principal], boolean>,
  'createCommunity' : ActorMethod<
    [string],
    { 'ok' : bigint } |
      { 'error' : string }
  >,
  'createCommunityPost' : ActorMethod<
    [bigint, string, string, [] | [ExternalBlob]],
    StandardResponse
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommunity' : ActorMethod<[bigint], [] | [Community]>,
  'getCommunityPosts' : ActorMethod<[bigint], Array<CommunityPost>>,
  'getMemberTabReorderPermissions' : ActorMethod<
    [bigint],
    Array<[Principal, boolean]>
  >,
  'getTabs' : ActorMethod<[bigint], Array<TabData>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'reorderTabs' : ActorMethod<[bigint, Array<Tab>], StandardResponse>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCommunitySettings' : ActorMethod<
    [
      bigint,
      [] | [ExternalBlob],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    StandardResponse
  >,
  'updateMemberTabReorderPermission' : ActorMethod<
    [bigint, Principal, boolean],
    StandardResponse
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];