/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TurnOrder {
    currentIndex: bigint;
    order: Array<string>;
    sessionId: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface JoinSessionRequest {
    nickname: string;
    password?: string;
    sessionId: bigint;
}
export interface ImageReference {
    id: bigint;
    createdBy: Principal;
    size: bigint;
    lastModified: bigint;
    fileId: string;
    caption: string;
    documentId: bigint;
    position: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type StandardResponse = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "error";
    error: string;
};
export interface PlayerDocument {
    id: bigint;
    content: string;
    owner: Principal;
    name: string;
    createdBy: Principal;
    lastModified: bigint;
    visible: boolean;
    sessionId: bigint;
    images: Array<ImageReference>;
}
export interface DocumentWithImages {
    id: bigint;
    content: string;
    name: string;
    createdBy: Principal;
    locked: boolean;
    lastModified: bigint;
    sessionId: bigint;
    revision: bigint;
    images: Array<ImageReference>;
}
export interface Document {
    id: bigint;
    content: string;
    name: string;
    createdBy: Principal;
    locked: boolean;
    lastModified: bigint;
    sessionId: bigint;
    revision: bigint;
}
export interface DiceRollResult {
    pattern: string;
    total: bigint;
    modifier: bigint;
    rolls: Array<bigint>;
}
export interface SessionMember {
    id: Principal;
    nickname: string;
    joinedAt: bigint;
}
export interface Session {
    id: bigint;
    members: Array<SessionMember>;
    host: Principal;
    name: string;
    createdAt: bigint;
    channels: Array<Channel>;
    passwordHash?: Uint8Array;
    lastActive: bigint;
}
export interface SessionExport {
    playerDocuments: Array<PlayerDocument>;
    turnOrder?: TurnOrder;
    documents: Array<Document>;
    messages: Array<Message>;
    channels: Array<Channel>;
    session: Session;
    images: Array<ImageReference>;
}
export interface Channel {
    id: bigint;
    name: string;
    createdBy: Principal;
}
export interface SessionCreateRequest {
    password?: string;
    name: string;
    hostNickname: string;
}
export interface PlayerDocumentMetadata {
    id: bigint;
    owner: Principal;
    name: string;
    createdBy: Principal;
    lastModified: bigint;
    visible: boolean;
    sessionId: bigint;
}
export interface Message {
    id: bigint;
    content: string;
    channelId: bigint;
    author: string;
    timestamp: bigint;
}
export interface UserProfile {
    name: string;
    profilePicture?: ExternalBlob;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addImageToDocument(sessionId: bigint, documentId: bigint, fileId: string, caption: string, position: bigint, size: bigint): Promise<StandardResponse>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createChannel(sessionId: bigint, name: string): Promise<StandardResponse>;
    createDocument(sessionId: bigint, name: string, content: string): Promise<StandardResponse>;
    createPlayerDocument(sessionId: bigint, name: string, content: string, visible: boolean): Promise<StandardResponse>;
    createSession(request: SessionCreateRequest): Promise<Session>;
    deleteChannel(sessionId: bigint, channelId: bigint): Promise<StandardResponse>;
    deleteDocument(documentId: bigint): Promise<StandardResponse>;
    deletePlayerDocument(documentId: bigint): Promise<StandardResponse>;
    editDocument(documentId: bigint, newContent: string): Promise<StandardResponse>;
    editPlayerDocument(documentId: bigint, newContent: string): Promise<StandardResponse>;
    exportSession(sessionId: bigint): Promise<SessionExport | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChannels(sessionId: bigint): Promise<Array<Channel>>;
    getDocument(documentId: bigint): Promise<Document | null>;
    getDocumentWithImages(documentId: bigint): Promise<DocumentWithImages | null>;
    getImageReferences(documentId: bigint): Promise<Array<ImageReference>>;
    getImages(sessionId: bigint): Promise<Array<ImageReference>>;
    getMessages(sessionId: bigint, channelId: bigint): Promise<Array<Message>>;
    getPlayerDocument(documentId: bigint): Promise<PlayerDocument | null>;
    getSession(sessionId: bigint): Promise<Session | null>;
    getTurnOrder(sessionId: bigint): Promise<TurnOrder | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    importSession(exportData: SessionExport): Promise<StandardResponse>;
    isCallerAdmin(): Promise<boolean>;
    joinSession(request: JoinSessionRequest): Promise<StandardResponse>;
    listDocuments(sessionId: bigint): Promise<Array<Document>>;
    listPlayerDocuments(sessionId: bigint): Promise<Array<PlayerDocument>>;
    listPlayerDocumentsMetadata(sessionId: bigint): Promise<Array<PlayerDocumentMetadata>>;
    listSessions(): Promise<Array<Session>>;
    lockDocument(documentId: bigint): Promise<StandardResponse>;
    nextTurn(sessionId: bigint): Promise<StandardResponse>;
    postMessage(sessionId: bigint, channelId: bigint, content: string): Promise<StandardResponse>;
    removeProfilePicture(): Promise<void>;
    renameChannel(sessionId: bigint, channelId: bigint, newName: string): Promise<StandardResponse>;
    renameDocument(documentId: bigint, newName: string): Promise<StandardResponse>;
    renamePlayerDocument(documentId: bigint, newName: string): Promise<StandardResponse>;
    roll(sessionId: bigint, pattern: string): Promise<DiceRollResult>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setPlayerDocumentVisibility(documentId: bigint, visible: boolean): Promise<StandardResponse>;
    setTurnOrder(sessionId: bigint, order: Array<string>): Promise<StandardResponse>;
    unlockDocument(documentId: bigint): Promise<StandardResponse>;
}
import type { Channel as _Channel, Document as _Document, DocumentWithImages as _DocumentWithImages, ExternalBlob as _ExternalBlob, ImageReference as _ImageReference, JoinSessionRequest as _JoinSessionRequest, Message as _Message, PlayerDocument as _PlayerDocument, Session as _Session, SessionCreateRequest as _SessionCreateRequest, SessionExport as _SessionExport, SessionMember as _SessionMember, StandardResponse as _StandardResponse, TurnOrder as _TurnOrder, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addImageToDocument(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: bigint, arg5: bigint): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.addImageToDocument(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addImageToDocument(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createChannel(arg0: bigint, arg1: string): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.createChannel(arg0, arg1);
                return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChannel(arg0, arg1);
            return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async createDocument(arg0: bigint, arg1: string, arg2: string): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.createDocument(arg0, arg1, arg2);
                return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDocument(arg0, arg1, arg2);
            return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPlayerDocument(arg0: bigint, arg1: string, arg2: string, arg3: boolean): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlayerDocument(arg0, arg1, arg2, arg3);
                return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlayerDocument(arg0, arg1, arg2, arg3);
            return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async createSession(arg0: SessionCreateRequest): Promise<Session> {
        if (this.processError) {
            try {
                const result = await this.actor.createSession(to_candid_SessionCreateRequest_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Session_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSession(to_candid_SessionCreateRequest_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Session_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteChannel(arg0: bigint, arg1: bigint): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChannel(arg0, arg1);
                return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChannel(arg0, arg1);
            return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteDocument(arg0: bigint): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDocument(arg0);
                return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDocument(arg0);
            return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async deletePlayerDocument(arg0: bigint): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePlayerDocument(arg0);
                return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePlayerDocument(arg0);
            return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async editDocument(arg0: bigint, arg1: string): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.editDocument(arg0, arg1);
                return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editDocument(arg0, arg1);
            return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async editPlayerDocument(arg0: bigint, arg1: string): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.editPlayerDocument(arg0, arg1);
                return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editPlayerDocument(arg0, arg1);
            return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async exportSession(arg0: bigint): Promise<SessionExport | null> {
        if (this.processError) {
            try {
                const result = await this.actor.exportSession(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportSession(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChannels(arg0: bigint): Promise<Array<Channel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChannels(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChannels(arg0);
            return result;
        }
    }
    async getDocument(arg0: bigint): Promise<Document | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocument(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocument(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocumentWithImages(arg0: bigint): Promise<DocumentWithImages | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocumentWithImages(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocumentWithImages(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getImageReferences(arg0: bigint): Promise<Array<ImageReference>> {
        if (this.processError) {
            try {
                const result = await this.actor.getImageReferences(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImageReferences(arg0);
            return result;
        }
    }
    async getImages(arg0: bigint): Promise<Array<ImageReference>> {
        if (this.processError) {
            try {
                const result = await this.actor.getImages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImages(arg0);
            return result;
        }
    }
    async getMessages(arg0: bigint, arg1: bigint): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0, arg1);
            return result;
        }
    }
    async getPlayerDocument(arg0: bigint): Promise<PlayerDocument | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerDocument(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerDocument(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSession(arg0: bigint): Promise<Session | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSession(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSession(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTurnOrder(arg0: bigint): Promise<TurnOrder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTurnOrder(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTurnOrder(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async importSession(arg0: SessionExport): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.importSession(to_candid_SessionExport_n32(this._uploadFile, this._downloadFile, arg0));
                return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importSession(to_candid_SessionExport_n32(this._uploadFile, this._downloadFile, arg0));
            return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinSession(arg0: JoinSessionRequest): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.joinSession(to_candid_JoinSessionRequest_n36(this._uploadFile, this._downloadFile, arg0));
                return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinSession(to_candid_JoinSessionRequest_n36(this._uploadFile, this._downloadFile, arg0));
            return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDocuments(arg0: bigint): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDocuments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDocuments(arg0);
            return result;
        }
    }
    async listPlayerDocuments(arg0: bigint): Promise<Array<PlayerDocument>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPlayerDocuments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPlayerDocuments(arg0);
            return result;
        }
    }
    async listPlayerDocumentsMetadata(arg0: bigint): Promise<Array<PlayerDocumentMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPlayerDocumentsMetadata(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPlayerDocumentsMetadata(arg0);
            return result;
        }
    }
    async listSessions(): Promise<Array<Session>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSessions();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSessions();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async lockDocument(arg0: bigint): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.lockDocument(arg0);
                return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.lockDocument(arg0);
            return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async nextTurn(arg0: bigint): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.nextTurn(arg0);
                return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.nextTurn(arg0);
            return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async postMessage(arg0: bigint, arg1: bigint, arg2: string): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.postMessage(arg0, arg1, arg2);
                return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postMessage(arg0, arg1, arg2);
            return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeProfilePicture(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeProfilePicture();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeProfilePicture();
            return result;
        }
    }
    async renameChannel(arg0: bigint, arg1: bigint, arg2: string): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.renameChannel(arg0, arg1, arg2);
                return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameChannel(arg0, arg1, arg2);
            return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async renameDocument(arg0: bigint, arg1: string): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.renameDocument(arg0, arg1);
                return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameDocument(arg0, arg1);
            return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async renamePlayerDocument(arg0: bigint, arg1: string): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.renamePlayerDocument(arg0, arg1);
                return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renamePlayerDocument(arg0, arg1);
            return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async roll(arg0: bigint, arg1: string): Promise<DiceRollResult> {
        if (this.processError) {
            try {
                const result = await this.actor.roll(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.roll(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n39(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n39(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setPlayerDocumentVisibility(arg0: bigint, arg1: boolean): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.setPlayerDocumentVisibility(arg0, arg1);
                return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPlayerDocumentVisibility(arg0, arg1);
            return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async setTurnOrder(arg0: bigint, arg1: Array<string>): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.setTurnOrder(arg0, arg1);
                return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTurnOrder(arg0, arg1);
            return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async unlockDocument(arg0: bigint): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.unlockDocument(arg0);
                return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlockDocument(arg0);
            return from_candid_StandardResponse_n8(this._uploadFile, this._downloadFile, result);
        }
    }
}
async function from_candid_ExternalBlob_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_SessionExport_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionExport): SessionExport {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Session_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Session): Session {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_StandardResponse_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StandardResponse): StandardResponse {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SessionExport]): SessionExport | null {
    return value.length === 0 ? null : from_candid_SessionExport_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TurnOrder]): TurnOrder | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n22(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Document]): Document | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DocumentWithImages]): DocumentWithImages | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerDocument]): PlayerDocument | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Session]): Session | null {
    return value.length === 0 ? null : from_candid_Session_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    members: Array<_SessionMember>;
    host: Principal;
    name: string;
    createdAt: bigint;
    channels: Array<_Channel>;
    passwordHash: [] | [Uint8Array];
    lastActive: bigint;
}): {
    id: bigint;
    members: Array<SessionMember>;
    host: Principal;
    name: string;
    createdAt: bigint;
    channels: Array<Channel>;
    passwordHash?: Uint8Array;
    lastActive: bigint;
} {
    return {
        id: value.id,
        members: value.members,
        host: value.host,
        name: value.name,
        createdAt: value.createdAt,
        channels: value.channels,
        passwordHash: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.passwordHash)),
        lastActive: value.lastActive
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    playerDocuments: Array<_PlayerDocument>;
    turnOrder: [] | [_TurnOrder];
    documents: Array<_Document>;
    messages: Array<_Message>;
    channels: Array<_Channel>;
    session: _Session;
    images: Array<_ImageReference>;
}): {
    playerDocuments: Array<PlayerDocument>;
    turnOrder?: TurnOrder;
    documents: Array<Document>;
    messages: Array<Message>;
    channels: Array<Channel>;
    session: Session;
    images: Array<ImageReference>;
} {
    return {
        playerDocuments: value.playerDocuments,
        turnOrder: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.turnOrder)),
        documents: value.documents,
        messages: value.messages,
        channels: value.channels,
        session: from_candid_Session_n14(_uploadFile, _downloadFile, value.session),
        images: value.images
    };
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    profilePicture: [] | [_ExternalBlob];
}): Promise<{
    name: string;
    profilePicture?: ExternalBlob;
}> {
    return {
        name: value.name,
        profilePicture: record_opt_to_undefined(await from_candid_opt_n24(_uploadFile, _downloadFile, value.profilePicture))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    error: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "error";
    error: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "error" in value ? {
        __kind__: "error",
        error: value.error
    } : value;
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Session>): Array<Session> {
    return value.map((x)=>from_candid_Session_n14(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_JoinSessionRequest_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JoinSessionRequest): _JoinSessionRequest {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_SessionCreateRequest_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionCreateRequest): _SessionCreateRequest {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_SessionExport_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionExport): _SessionExport {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_Session_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Session): _Session {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    password?: string;
    name: string;
    hostNickname: string;
}): {
    password: [] | [string];
    name: string;
    hostNickname: string;
} {
    return {
        password: value.password ? candid_some(value.password) : candid_none(),
        name: value.name,
        hostNickname: value.hostNickname
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    playerDocuments: Array<PlayerDocument>;
    turnOrder?: TurnOrder;
    documents: Array<Document>;
    messages: Array<Message>;
    channels: Array<Channel>;
    session: Session;
    images: Array<ImageReference>;
}): {
    playerDocuments: Array<_PlayerDocument>;
    turnOrder: [] | [_TurnOrder];
    documents: Array<_Document>;
    messages: Array<_Message>;
    channels: Array<_Channel>;
    session: _Session;
    images: Array<_ImageReference>;
} {
    return {
        playerDocuments: value.playerDocuments,
        turnOrder: value.turnOrder ? candid_some(value.turnOrder) : candid_none(),
        documents: value.documents,
        messages: value.messages,
        channels: value.channels,
        session: to_candid_Session_n34(_uploadFile, _downloadFile, value.session),
        images: value.images
    };
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    members: Array<SessionMember>;
    host: Principal;
    name: string;
    createdAt: bigint;
    channels: Array<Channel>;
    passwordHash?: Uint8Array;
    lastActive: bigint;
}): {
    id: bigint;
    members: Array<_SessionMember>;
    host: Principal;
    name: string;
    createdAt: bigint;
    channels: Array<_Channel>;
    passwordHash: [] | [Uint8Array];
    lastActive: bigint;
} {
    return {
        id: value.id,
        members: value.members,
        host: value.host,
        name: value.name,
        createdAt: value.createdAt,
        channels: value.channels,
        passwordHash: value.passwordHash ? candid_some(value.passwordHash) : candid_none(),
        lastActive: value.lastActive
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nickname: string;
    password?: string;
    sessionId: bigint;
}): {
    nickname: string;
    password: [] | [string];
    sessionId: bigint;
} {
    return {
        nickname: value.nickname,
        password: value.password ? candid_some(value.password) : candid_none(),
        sessionId: value.sessionId
    };
}
async function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    profilePicture?: ExternalBlob;
}): Promise<{
    name: string;
    profilePicture: [] | [_ExternalBlob];
}> {
    return {
        name: value.name,
        profilePicture: value.profilePicture ? candid_some(await to_candid_ExternalBlob_n41(_uploadFile, _downloadFile, value.profilePicture)) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
