/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type CreatePlayerDocumentResponse = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "error";
    error: string;
};
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Document {
    id: bigint;
    content: string;
    name: string;
    createdBy: Principal;
    locked: boolean;
    lastModified: bigint;
    sessionId: bigint;
    revision: bigint;
}
export interface DocumentWithImages {
    id: bigint;
    content: string;
    name: string;
    createdBy: Principal;
    locked: boolean;
    lastModified: bigint;
    sessionId: bigint;
    revision: bigint;
    images: Array<ImageReference>;
}
export type CreateDocumentResponse = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "error";
    error: string;
};
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PlayerDocument {
    id: bigint;
    content: string;
    owner: Principal;
    name: string;
    createdBy: Principal;
    lastModified: bigint;
    isPrivate: boolean;
    sessionId: bigint;
    images: Array<ImageReference>;
}
export type UploadDocumentFileResponse = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "error";
    error: string;
};
export interface Session {
    id: bigint;
    members: Array<SessionMember>;
    host: Principal;
    name: string;
    createdAt: bigint;
    channels: Array<Channel>;
    membersChannels: Array<MembersChannel>;
    passwordHash?: Uint8Array;
    lastActive: bigint;
}
export interface UploadFileRequest {
    file: ExternalBlob;
    size: bigint;
    mimeType: string;
    filename: string;
    documentId: bigint;
}
export interface SessionExport {
    playerDocuments: Array<PlayerDocument>;
    turnOrder?: TurnOrder;
    documents: Array<Document>;
    messages: Array<Message>;
    channels: Array<Channel>;
    session: Session;
    documentFiles: Array<DocumentFileReference>;
    images: Array<ImageReference>;
}
export interface SessionCreateRequest {
    password?: string;
    name: string;
    hostNickname: string;
}
export interface PlayerDocumentMetadata {
    id: bigint;
    owner: Principal;
    name: string;
    createdBy: Principal;
    lastModified: bigint;
    isPrivate: boolean;
    sessionId: bigint;
}
export interface DocumentComment {
    id: bigint;
    text: string;
    author: Principal;
    timestamp: Time;
    documentId: bigint;
}
export interface TurnOrder {
    currentIndex: bigint;
    order: Array<string>;
    sessionId: bigint;
}
export interface MembersChannel {
    id: bigint;
    name: string;
    createdBy: Principal;
}
export interface DocumentFileReference {
    id: bigint;
    file: ExternalBlob;
    createdBy: Principal;
    size: bigint;
    mimeType: string;
    filename: string;
    lastModified: bigint;
    documentId: bigint;
}
export interface JoinSessionRequest {
    nickname: string;
    password?: string;
    sessionId: bigint;
}
export interface ImageReference {
    id: bigint;
    title: string;
    createdBy: Principal;
    size: bigint;
    lastModified: bigint;
    fileId: string;
    caption: string;
    documentId: bigint;
    position: bigint;
}
export interface Channel {
    id: bigint;
    name: string;
    createdBy: Principal;
}
export type StandardResponse = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "error";
    error: string;
};
export interface DiceRollResult {
    pattern: string;
    total: bigint;
    modifier: bigint;
    rolls: Array<bigint>;
}
export interface SessionMember {
    id: Principal;
    nickname: string;
    joinedAt: bigint;
}
export interface Message {
    id: bigint;
    content: string;
    channelId: bigint;
    author: string;
    timestamp: bigint;
    image?: ExternalBlob;
    replyToId?: bigint;
}
export type AddImageToDocumentResponse = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "error";
    error: string;
};
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
    profilePicture?: ExternalBlob;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addComment(documentId: bigint, text: string): Promise<bigint>;
    addImageToDocument(sessionId: bigint, documentId: bigint, fileId: string, title: string, caption: string, position: bigint, size: bigint): Promise<AddImageToDocumentResponse>;
    addImageToPlayerDocument(documentId: bigint, fileId: string, title: string, caption: string, position: bigint, size: bigint): Promise<AddImageToDocumentResponse>;
    addPlayerImage(documentId: bigint, fileId: string, title: string, caption: string, position: bigint, size: bigint): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createChannel(sessionId: bigint, name: string): Promise<StandardResponse>;
    createDocument(sessionId: bigint, name: string, content: string): Promise<CreateDocumentResponse>;
    createMembersChannel(sessionId: bigint, name: string): Promise<StandardResponse>;
    createPlayerDocument(sessionId: bigint, name: string, content: string, isPrivate: boolean): Promise<CreatePlayerDocumentResponse>;
    createSession(request: SessionCreateRequest): Promise<Session>;
    deleteChannel(sessionId: bigint, channelId: bigint): Promise<StandardResponse>;
    deleteComment(commentId: bigint): Promise<void>;
    deleteDocument(documentId: bigint): Promise<StandardResponse>;
    deleteMembersChannel(sessionId: bigint, channelId: bigint): Promise<StandardResponse>;
    deletePlayerDocument(documentId: bigint): Promise<StandardResponse>;
    editDocument(documentId: bigint, newContent: string): Promise<StandardResponse>;
    editPlayerDocument(documentId: bigint, newContent: string): Promise<StandardResponse>;
    exportSession(sessionId: bigint): Promise<SessionExport | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChannels(sessionId: bigint): Promise<Array<Channel>>;
    getComments(documentId: bigint): Promise<Array<DocumentComment>>;
    getDocument(documentId: bigint): Promise<Document | null>;
    getDocumentFileBlob(fileId: bigint): Promise<ExternalBlob | null>;
    getDocumentFileReference(fileId: bigint): Promise<DocumentFileReference | null>;
    getDocumentWithImages(documentId: bigint): Promise<DocumentWithImages | null>;
    getImageReferences(documentId: bigint): Promise<Array<ImageReference>>;
    getImages(sessionId: bigint): Promise<Array<ImageReference>>;
    getMembersChannels(sessionId: bigint): Promise<Array<MembersChannel>>;
    getMessages(sessionId: bigint, channelId: bigint): Promise<Array<Message>>;
    getPlayerDocument(documentId: bigint): Promise<PlayerDocument | null>;
    getSession(sessionId: bigint): Promise<Session | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    importSession(exportData: SessionExport): Promise<StandardResponse>;
    isCallerAdmin(): Promise<boolean>;
    joinSession(request: JoinSessionRequest): Promise<StandardResponse>;
    listDocumentFiles(documentId: bigint): Promise<Array<DocumentFileReference>>;
    listDocuments(sessionId: bigint): Promise<Array<Document>>;
    listPlayerDocuments(sessionId: bigint): Promise<Array<PlayerDocument>>;
    listPlayerDocumentsMetadata(sessionId: bigint): Promise<Array<PlayerDocumentMetadata>>;
    listSessions(): Promise<Array<Session>>;
    lockDocument(documentId: bigint): Promise<StandardResponse>;
    nextTurn(sessionId: bigint): Promise<StandardResponse>;
    postMessage(sessionId: bigint, channelId: bigint, content: string, image: ExternalBlob | null, replyToId: bigint | null): Promise<StandardResponse>;
    removeProfilePicture(): Promise<void>;
    renameChannel(sessionId: bigint, channelId: bigint, newName: string): Promise<StandardResponse>;
    renameDocument(documentId: bigint, newName: string): Promise<StandardResponse>;
    renameMembersChannel(sessionId: bigint, channelId: bigint, newName: string): Promise<StandardResponse>;
    renamePlayerDocument(documentId: bigint, newName: string): Promise<StandardResponse>;
    roll(sessionId: bigint, pattern: string): Promise<DiceRollResult>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setPlayerDocumentVisibility(documentId: bigint, isPrivate: boolean): Promise<StandardResponse>;
    setTurnOrder(sessionId: bigint, order: Array<string>): Promise<StandardResponse>;
    unlockDocument(documentId: bigint): Promise<StandardResponse>;
    updateComment(commentId: bigint, text: string): Promise<void>;
    uploadDocumentFile(request: UploadFileRequest): Promise<UploadDocumentFileResponse>;
}
import type { AddImageToDocumentResponse as _AddImageToDocumentResponse, Channel as _Channel, CreateDocumentResponse as _CreateDocumentResponse, CreatePlayerDocumentResponse as _CreatePlayerDocumentResponse, Document as _Document, DocumentFileReference as _DocumentFileReference, DocumentWithImages as _DocumentWithImages, ExternalBlob as _ExternalBlob, ImageReference as _ImageReference, JoinSessionRequest as _JoinSessionRequest, MembersChannel as _MembersChannel, Message as _Message, PlayerDocument as _PlayerDocument, Session as _Session, SessionCreateRequest as _SessionCreateRequest, SessionExport as _SessionExport, SessionMember as _SessionMember, StandardResponse as _StandardResponse, TurnOrder as _TurnOrder, UploadDocumentFileResponse as _UploadDocumentFileResponse, UploadFileRequest as _UploadFileRequest, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addComment(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return result;
        }
    }
    async addImageToDocument(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: bigint): Promise<AddImageToDocumentResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.addImageToDocument(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return from_candid_AddImageToDocumentResponse_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addImageToDocument(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return from_candid_AddImageToDocumentResponse_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async addImageToPlayerDocument(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: bigint): Promise<AddImageToDocumentResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.addImageToPlayerDocument(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_AddImageToDocumentResponse_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addImageToPlayerDocument(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_AddImageToDocumentResponse_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async addPlayerImage(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPlayerImage(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPlayerImage(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createChannel(arg0: bigint, arg1: string): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.createChannel(arg0, arg1);
                return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChannel(arg0, arg1);
            return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async createDocument(arg0: bigint, arg1: string, arg2: string): Promise<CreateDocumentResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.createDocument(arg0, arg1, arg2);
                return from_candid_CreateDocumentResponse_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDocument(arg0, arg1, arg2);
            return from_candid_CreateDocumentResponse_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async createMembersChannel(arg0: bigint, arg1: string): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.createMembersChannel(arg0, arg1);
                return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMembersChannel(arg0, arg1);
            return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPlayerDocument(arg0: bigint, arg1: string, arg2: string, arg3: boolean): Promise<CreatePlayerDocumentResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlayerDocument(arg0, arg1, arg2, arg3);
                return from_candid_CreatePlayerDocumentResponse_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlayerDocument(arg0, arg1, arg2, arg3);
            return from_candid_CreatePlayerDocumentResponse_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async createSession(arg0: SessionCreateRequest): Promise<Session> {
        if (this.processError) {
            try {
                const result = await this.actor.createSession(to_candid_SessionCreateRequest_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Session_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSession(to_candid_SessionCreateRequest_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Session_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteChannel(arg0: bigint, arg1: bigint): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChannel(arg0, arg1);
                return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChannel(arg0, arg1);
            return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteComment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0);
            return result;
        }
    }
    async deleteDocument(arg0: bigint): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDocument(arg0);
                return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDocument(arg0);
            return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteMembersChannel(arg0: bigint, arg1: bigint): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMembersChannel(arg0, arg1);
                return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMembersChannel(arg0, arg1);
            return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async deletePlayerDocument(arg0: bigint): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePlayerDocument(arg0);
                return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePlayerDocument(arg0);
            return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async editDocument(arg0: bigint, arg1: string): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.editDocument(arg0, arg1);
                return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editDocument(arg0, arg1);
            return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async editPlayerDocument(arg0: bigint, arg1: string): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.editPlayerDocument(arg0, arg1);
                return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editPlayerDocument(arg0, arg1);
            return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async exportSession(arg0: bigint): Promise<SessionExport | null> {
        if (this.processError) {
            try {
                const result = await this.actor.exportSession(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportSession(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChannels(arg0: bigint): Promise<Array<Channel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChannels(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChannels(arg0);
            return result;
        }
    }
    async getComments(arg0: bigint): Promise<Array<DocumentComment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComments(arg0);
            return result;
        }
    }
    async getDocument(arg0: bigint): Promise<Document | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocument(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocument(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocumentFileBlob(arg0: bigint): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocumentFileBlob(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocumentFileBlob(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocumentFileReference(arg0: bigint): Promise<DocumentFileReference | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocumentFileReference(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocumentFileReference(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocumentWithImages(arg0: bigint): Promise<DocumentWithImages | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocumentWithImages(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocumentWithImages(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getImageReferences(arg0: bigint): Promise<Array<ImageReference>> {
        if (this.processError) {
            try {
                const result = await this.actor.getImageReferences(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImageReferences(arg0);
            return result;
        }
    }
    async getImages(arg0: bigint): Promise<Array<ImageReference>> {
        if (this.processError) {
            try {
                const result = await this.actor.getImages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImages(arg0);
            return result;
        }
    }
    async getMembersChannels(arg0: bigint): Promise<Array<MembersChannel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMembersChannels(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMembersChannels(arg0);
            return result;
        }
    }
    async getMessages(arg0: bigint, arg1: bigint): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0, arg1);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0, arg1);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerDocument(arg0: bigint): Promise<PlayerDocument | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerDocument(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerDocument(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSession(arg0: bigint): Promise<Session | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSession(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSession(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async importSession(arg0: SessionExport): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.importSession(await to_candid_SessionExport_n43(this._uploadFile, this._downloadFile, arg0));
                return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importSession(await to_candid_SessionExport_n43(this._uploadFile, this._downloadFile, arg0));
            return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinSession(arg0: JoinSessionRequest): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.joinSession(to_candid_JoinSessionRequest_n54(this._uploadFile, this._downloadFile, arg0));
                return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinSession(to_candid_JoinSessionRequest_n54(this._uploadFile, this._downloadFile, arg0));
            return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDocumentFiles(arg0: bigint): Promise<Array<DocumentFileReference>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDocumentFiles(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDocumentFiles(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDocuments(arg0: bigint): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDocuments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDocuments(arg0);
            return result;
        }
    }
    async listPlayerDocuments(arg0: bigint): Promise<Array<PlayerDocument>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPlayerDocuments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPlayerDocuments(arg0);
            return result;
        }
    }
    async listPlayerDocumentsMetadata(arg0: bigint): Promise<Array<PlayerDocumentMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPlayerDocumentsMetadata(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPlayerDocumentsMetadata(arg0);
            return result;
        }
    }
    async listSessions(): Promise<Array<Session>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSessions();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSessions();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async lockDocument(arg0: bigint): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.lockDocument(arg0);
                return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.lockDocument(arg0);
            return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async nextTurn(arg0: bigint): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.nextTurn(arg0);
                return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.nextTurn(arg0);
            return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async postMessage(arg0: bigint, arg1: bigint, arg2: string, arg3: ExternalBlob | null, arg4: bigint | null): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.postMessage(arg0, arg1, arg2, await to_candid_opt_n57(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n58(this._uploadFile, this._downloadFile, arg4));
                return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postMessage(arg0, arg1, arg2, await to_candid_opt_n57(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n58(this._uploadFile, this._downloadFile, arg4));
            return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeProfilePicture(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeProfilePicture();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeProfilePicture();
            return result;
        }
    }
    async renameChannel(arg0: bigint, arg1: bigint, arg2: string): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.renameChannel(arg0, arg1, arg2);
                return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameChannel(arg0, arg1, arg2);
            return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async renameDocument(arg0: bigint, arg1: string): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.renameDocument(arg0, arg1);
                return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameDocument(arg0, arg1);
            return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async renameMembersChannel(arg0: bigint, arg1: bigint, arg2: string): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.renameMembersChannel(arg0, arg1, arg2);
                return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameMembersChannel(arg0, arg1, arg2);
            return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async renamePlayerDocument(arg0: bigint, arg1: string): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.renamePlayerDocument(arg0, arg1);
                return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renamePlayerDocument(arg0, arg1);
            return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async roll(arg0: bigint, arg1: string): Promise<DiceRollResult> {
        if (this.processError) {
            try {
                const result = await this.actor.roll(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.roll(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n59(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n59(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setPlayerDocumentVisibility(arg0: bigint, arg1: boolean): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.setPlayerDocumentVisibility(arg0, arg1);
                return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPlayerDocumentVisibility(arg0, arg1);
            return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async setTurnOrder(arg0: bigint, arg1: Array<string>): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.setTurnOrder(arg0, arg1);
                return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTurnOrder(arg0, arg1);
            return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async unlockDocument(arg0: bigint): Promise<StandardResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.unlockDocument(arg0);
                return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlockDocument(arg0);
            return from_candid_StandardResponse_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateComment(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateComment(arg0, arg1);
            return result;
        }
    }
    async uploadDocumentFile(arg0: UploadFileRequest): Promise<UploadDocumentFileResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadDocumentFile(await to_candid_UploadFileRequest_n61(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UploadDocumentFileResponse_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadDocumentFile(await to_candid_UploadFileRequest_n61(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UploadDocumentFileResponse_n63(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AddImageToDocumentResponse_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AddImageToDocumentResponse): AddImageToDocumentResponse {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_CreateDocumentResponse_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreateDocumentResponse): CreateDocumentResponse {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_CreatePlayerDocumentResponse_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreatePlayerDocumentResponse): CreatePlayerDocumentResponse {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
async function from_candid_DocumentFileReference_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentFileReference): Promise<DocumentFileReference> {
    return await from_candid_record_n32(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_Message_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Promise<Message> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_SessionExport_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionExport): Promise<SessionExport> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Session_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Session): Session {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_StandardResponse_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StandardResponse): StandardResponse {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UploadDocumentFileResponse_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UploadDocumentFileResponse): UploadDocumentFileResponse {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SessionExport]): Promise<SessionExport | null> {
    return value.length === 0 ? null : await from_candid_SessionExport_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TurnOrder]): TurnOrder | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Document]): Document | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DocumentFileReference]): Promise<DocumentFileReference | null> {
    return value.length === 0 ? null : await from_candid_DocumentFileReference_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DocumentWithImages]): DocumentWithImages | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerDocument]): PlayerDocument | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Session]): Session | null {
    return value.length === 0 ? null : from_candid_Session_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    members: Array<_SessionMember>;
    host: Principal;
    name: string;
    createdAt: bigint;
    channels: Array<_Channel>;
    membersChannels: Array<_MembersChannel>;
    passwordHash: [] | [Uint8Array];
    lastActive: bigint;
}): {
    id: bigint;
    members: Array<SessionMember>;
    host: Principal;
    name: string;
    createdAt: bigint;
    channels: Array<Channel>;
    membersChannels: Array<MembersChannel>;
    passwordHash?: Uint8Array;
    lastActive: bigint;
} {
    return {
        id: value.id,
        members: value.members,
        host: value.host,
        name: value.name,
        createdAt: value.createdAt,
        channels: value.channels,
        membersChannels: value.membersChannels,
        passwordHash: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.passwordHash)),
        lastActive: value.lastActive
    };
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    playerDocuments: Array<_PlayerDocument>;
    turnOrder: [] | [_TurnOrder];
    documents: Array<_Document>;
    messages: Array<_Message>;
    channels: Array<_Channel>;
    session: _Session;
    documentFiles: Array<_DocumentFileReference>;
    images: Array<_ImageReference>;
}): Promise<{
    playerDocuments: Array<PlayerDocument>;
    turnOrder?: TurnOrder;
    documents: Array<Document>;
    messages: Array<Message>;
    channels: Array<Channel>;
    session: Session;
    documentFiles: Array<DocumentFileReference>;
    images: Array<ImageReference>;
}> {
    return {
        playerDocuments: value.playerDocuments,
        turnOrder: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.turnOrder)),
        documents: value.documents,
        messages: await from_candid_vec_n25(_uploadFile, _downloadFile, value.messages),
        channels: value.channels,
        session: from_candid_Session_n18(_uploadFile, _downloadFile, value.session),
        documentFiles: await from_candid_vec_n30(_uploadFile, _downloadFile, value.documentFiles),
        images: value.images
    };
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    channelId: bigint;
    author: string;
    timestamp: bigint;
    image: [] | [_ExternalBlob];
    replyToId: [] | [bigint];
}): Promise<{
    id: bigint;
    content: string;
    channelId: bigint;
    author: string;
    timestamp: bigint;
    image?: ExternalBlob;
    replyToId?: bigint;
}> {
    return {
        id: value.id,
        content: value.content,
        channelId: value.channelId,
        author: value.author,
        timestamp: value.timestamp,
        image: record_opt_to_undefined(await from_candid_opt_n28(_uploadFile, _downloadFile, value.image)),
        replyToId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.replyToId))
    };
}
async function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    file: _ExternalBlob;
    createdBy: Principal;
    size: bigint;
    mimeType: string;
    filename: string;
    lastModified: bigint;
    documentId: bigint;
}): Promise<{
    id: bigint;
    file: ExternalBlob;
    createdBy: Principal;
    size: bigint;
    mimeType: string;
    filename: string;
    lastModified: bigint;
    documentId: bigint;
}> {
    return {
        id: value.id,
        file: await from_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value.file),
        createdBy: value.createdBy,
        size: value.size,
        mimeType: value.mimeType,
        filename: value.filename,
        lastModified: value.lastModified,
        documentId: value.documentId
    };
}
async function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    profilePicture: [] | [_ExternalBlob];
}): Promise<{
    name: string;
    profilePicture?: ExternalBlob;
}> {
    return {
        name: value.name,
        profilePicture: record_opt_to_undefined(await from_candid_opt_n28(_uploadFile, _downloadFile, value.profilePicture))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    error: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "error";
    error: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "error" in value ? {
        __kind__: "error",
        error: value.error
    } : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    error: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "error";
    error: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "error" in value ? {
        __kind__: "error",
        error: value.error
    } : value;
}
async function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Promise<Array<Message>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Message_n26(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DocumentFileReference>): Promise<Array<DocumentFileReference>> {
    return await Promise.all(value.map(async (x)=>await from_candid_DocumentFileReference_n31(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Session>): Array<Session> {
    return value.map((x)=>from_candid_Session_n18(_uploadFile, _downloadFile, x));
}
async function to_candid_DocumentFileReference_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentFileReference): Promise<_DocumentFileReference> {
    return await to_candid_record_n53(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_JoinSessionRequest_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JoinSessionRequest): _JoinSessionRequest {
    return to_candid_record_n55(_uploadFile, _downloadFile, value);
}
async function to_candid_Message_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Message): Promise<_Message> {
    return await to_candid_record_n47(_uploadFile, _downloadFile, value);
}
function to_candid_SessionCreateRequest_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionCreateRequest): _SessionCreateRequest {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function to_candid_SessionExport_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionExport): Promise<_SessionExport> {
    return await to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_Session_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Session): _Session {
    return to_candid_record_n50(_uploadFile, _downloadFile, value);
}
async function to_candid_UploadFileRequest_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UploadFileRequest): Promise<_UploadFileRequest> {
    return await to_candid_record_n62(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n60(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n48(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    password?: string;
    name: string;
    hostNickname: string;
}): {
    password: [] | [string];
    name: string;
    hostNickname: string;
} {
    return {
        password: value.password ? candid_some(value.password) : candid_none(),
        name: value.name,
        hostNickname: value.hostNickname
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    playerDocuments: Array<PlayerDocument>;
    turnOrder?: TurnOrder;
    documents: Array<Document>;
    messages: Array<Message>;
    channels: Array<Channel>;
    session: Session;
    documentFiles: Array<DocumentFileReference>;
    images: Array<ImageReference>;
}): Promise<{
    playerDocuments: Array<_PlayerDocument>;
    turnOrder: [] | [_TurnOrder];
    documents: Array<_Document>;
    messages: Array<_Message>;
    channels: Array<_Channel>;
    session: _Session;
    documentFiles: Array<_DocumentFileReference>;
    images: Array<_ImageReference>;
}> {
    return {
        playerDocuments: value.playerDocuments,
        turnOrder: value.turnOrder ? candid_some(value.turnOrder) : candid_none(),
        documents: value.documents,
        messages: await to_candid_vec_n45(_uploadFile, _downloadFile, value.messages),
        channels: value.channels,
        session: to_candid_Session_n49(_uploadFile, _downloadFile, value.session),
        documentFiles: await to_candid_vec_n51(_uploadFile, _downloadFile, value.documentFiles),
        images: value.images
    };
}
async function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    channelId: bigint;
    author: string;
    timestamp: bigint;
    image?: ExternalBlob;
    replyToId?: bigint;
}): Promise<{
    id: bigint;
    content: string;
    channelId: bigint;
    author: string;
    timestamp: bigint;
    image: [] | [_ExternalBlob];
    replyToId: [] | [bigint];
}> {
    return {
        id: value.id,
        content: value.content,
        channelId: value.channelId,
        author: value.author,
        timestamp: value.timestamp,
        image: value.image ? candid_some(await to_candid_ExternalBlob_n48(_uploadFile, _downloadFile, value.image)) : candid_none(),
        replyToId: value.replyToId ? candid_some(value.replyToId) : candid_none()
    };
}
function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    members: Array<SessionMember>;
    host: Principal;
    name: string;
    createdAt: bigint;
    channels: Array<Channel>;
    membersChannels: Array<MembersChannel>;
    passwordHash?: Uint8Array;
    lastActive: bigint;
}): {
    id: bigint;
    members: Array<_SessionMember>;
    host: Principal;
    name: string;
    createdAt: bigint;
    channels: Array<_Channel>;
    membersChannels: Array<_MembersChannel>;
    passwordHash: [] | [Uint8Array];
    lastActive: bigint;
} {
    return {
        id: value.id,
        members: value.members,
        host: value.host,
        name: value.name,
        createdAt: value.createdAt,
        channels: value.channels,
        membersChannels: value.membersChannels,
        passwordHash: value.passwordHash ? candid_some(value.passwordHash) : candid_none(),
        lastActive: value.lastActive
    };
}
async function to_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    file: ExternalBlob;
    createdBy: Principal;
    size: bigint;
    mimeType: string;
    filename: string;
    lastModified: bigint;
    documentId: bigint;
}): Promise<{
    id: bigint;
    file: _ExternalBlob;
    createdBy: Principal;
    size: bigint;
    mimeType: string;
    filename: string;
    lastModified: bigint;
    documentId: bigint;
}> {
    return {
        id: value.id,
        file: await to_candid_ExternalBlob_n48(_uploadFile, _downloadFile, value.file),
        createdBy: value.createdBy,
        size: value.size,
        mimeType: value.mimeType,
        filename: value.filename,
        lastModified: value.lastModified,
        documentId: value.documentId
    };
}
function to_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nickname: string;
    password?: string;
    sessionId: bigint;
}): {
    nickname: string;
    password: [] | [string];
    sessionId: bigint;
} {
    return {
        nickname: value.nickname,
        password: value.password ? candid_some(value.password) : candid_none(),
        sessionId: value.sessionId
    };
}
async function to_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    profilePicture?: ExternalBlob;
}): Promise<{
    name: string;
    profilePicture: [] | [_ExternalBlob];
}> {
    return {
        name: value.name,
        profilePicture: value.profilePicture ? candid_some(await to_candid_ExternalBlob_n48(_uploadFile, _downloadFile, value.profilePicture)) : candid_none()
    };
}
async function to_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    file: ExternalBlob;
    size: bigint;
    mimeType: string;
    filename: string;
    documentId: bigint;
}): Promise<{
    file: _ExternalBlob;
    size: bigint;
    mimeType: string;
    filename: string;
    documentId: bigint;
}> {
    return {
        file: await to_candid_ExternalBlob_n48(_uploadFile, _downloadFile, value.file),
        size: value.size,
        mimeType: value.mimeType,
        filename: value.filename,
        documentId: value.documentId
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Message>): Promise<Array<_Message>> {
    return await Promise.all(value.map(async (x)=>await to_candid_Message_n46(_uploadFile, _downloadFile, x)));
}
async function to_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<DocumentFileReference>): Promise<Array<_DocumentFileReference>> {
    return await Promise.all(value.map(async (x)=>await to_candid_DocumentFileReference_n52(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
